### ISSUE TITLE
Not usable with unsized types?

### ISSUE THREAD

**Issue by rljacobson** [diwic/reffers-rs#11]
The `reffers::*::Strong<T>` type marks `T` as `?Sized`, but `T` must also implement `reffers::rc::Repr`, an "implementation detail." Except `Repr` apparently requires `T` to be either `str`, `[U]`, or `Sized`. 

So this smart pointer only works with sized types except for `str` and `[U]`? Am I missing something?

**Comment by diwic** [comment]
If you're referring to `dyn Trait` types then you're correct. The reason was that there was no way to get hold of what I needed without using nightly features. Maybe that has changed in the last year or two; I haven't followed Rust std development recently.

**Comment by rljacobson** [comment]
Thank you for the information, @diwic. Thanks for sharing your software. I'll close the ticket.
