### ISSUE TITLE
Send version of ARef

### ISSUE THREAD

**Issue by scottlamb** [diwic/reffers-rs#2]
hyper's new async API allows me to send my HTTP response via a `futures::Stream<Item = Chunk, Error = hyper::Error>`, where `Chunk` can be anything that satisfies `'static + Send + AsRef<[u8]>`. I'd like my `Chunk` type to be something like `ARef<[u8]>`.

This would let me (among other things) use mmaped memory without extra copies, trim the beginning and end of a `Vec<u8>` before passing it along, etc. More motivation [here](https://github.com/hyperium/hyper/issues/953#issuecomment-274410745). I talked about `owning_ref` there, but I think `ARef` is even better because I don't have to wrap it in an enum.

The problem is that `ARef<[u8]>` isn't `Send`. Maybe there should be a parallel type that is?

**Comment by diwic** [comment]
Yes, this makes a lot of sense to me. Implemented now. Enjoy!
